# Generated by Django 2.2 on 2021-02-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
    ]
